= 0.2.0 -> 0.3.0

== Changes

=== General
coff:ee update 1.2.1 → 1.3.0

=== roaster-hibernate
In the `EntityManagerProducer` class, the `EntityManagerFactory` injection has been deleted and the
The `produceDefaultEntityManager()` method itself produces it when needed.
So from now on it will only be created with default settings `EntityManagerFactory`,
if `@HibernatePersistenceConfig` is injected without an annotation for `EntityManager`.

=== Migration
The changes will not result in any migration work, it is backwards compatible.

=== roaster-tm4j
* Bugfix: Multiple tests when running maven no longer come with exception
* Bugfix: TM4J `Executed by` value is reloaded by tests
* TM4J environment value is loaded based on the config parameter of the tests

=== Migration
* The test class (or its ancestor) must be annotated with `@TestInstance(TestInstance.Lifecycle.PER_CLASS)`
* If does not exist, the given value in the config parameter `roaster.tm4j.environment` needs to be created on TM4J surface.