= Oracle DB

To use the Oracle DB module, you just need to include a reference in pom.xml

[source,xml]
.pom.xml
----
<dependency>
    <groupId>hu.icellmobilsoft.roaster</groupId>
    <artifactId>roaster-oracle</artifactId>
</dependency>
----

== Oracle DB Configuration parameters

The microprofile-config is used to parameterize the data needed to access the Oracle DB.

Examples:

[source,properties]
.META-INF/microprofile-config.properties
----
roaster.datasource.oracle.application.url=jdbc:oracle:thin:@//oracle.icellmobilsoft.hu:1521/sample
roaster.datasource.oracle.application.user=db_user
roaster.datasource.oracle.application.password=db_pass
----

[source,yml]
.META-INF/roaster-defaults.yml
----
roaster:
    datasource:
        oracle:
            application:
                url: jdbc:oracle:thin:@//oracle.icellmobilsoft.hu:1521/sample
                user: db_user
                password: db_pass
                maximumPoolSize: 10 #<1>
----
<1> (Optional) max size of connection pool (default: 5)

== Using OracleJDBCSelectorService

First, the service department must be injected.

[source,java]
.inject OracleJDBCSelectorService
----
    @Inject
    @DBConnection(configKey = DBConstants.Schema.APPLICATION)
    private OracleJDBCSelectorService service;
----

=== OracleJDBCSelectorService operations

The operations are available through OracleJDBCSelectorService, which, when invoked, creates a new connection to the database if there is no open connection, and then closes it at the end of the operation.

IMPORTANT: Methods starting with select will only accept sql statements starting with SELECT!
And selectFirst returns only the first row if there are multiple hits from DB.

* selectFirstStringValue(sql select string, columnName)
* selectFirstIntegerValue(sql select string, columnName)
* selectFirstBooleanValue(sql select string, columnName)
* selectFirstBigDecimalValue(sql select string, columnName)
* selectFirstDateValue(sql select string, columnName)
* selectRowCount(sql select string)
* selectFirstObject(sql select string, converter)
* selectAllObjects(sql select string, converter)

[source,java]
.example of operation calls
----
String name = service.selectFirstStringValue("SELECT deeepl_api_script.sh modules-api.adoc modules-api.translated.adoc modules-db.adoc modules-db.translated.adoc modules-hibernate.adoc modules-jaxrs.adoc modules-mongodb.adoc modules-redis.adoc modules-restassured.adoc modules-selenide.adoc modules-tm4j.adoc modules-zephyr.adoc modules.adoc FROM EXAMPLE WHERE X__ID = '0'", "NAME");
int rowCount = service.selectRowCount("SELECT deeepl_api_script.sh modules-api.adoc modules-api.translated.adoc modules-db.adoc modules-db.translated.adoc modules-hibernate.adoc modules-jaxrs.adoc modules-mongodb.adoc modules-redis.adoc modules-restassured.adoc modules-selenide.adoc modules-tm4j.adoc modules-zephyr.adoc modules.adoc FROM EXAMPLE WHERE X__ID = '0'");
List<Example> exampleList = service.selectAllObjects("SELECT deeepl_api_script.sh modules-api.adoc modules-api.translated.adoc modules-db.adoc modules-db.translated.adoc modules-hibernate.adoc modules-jaxrs.adoc modules-mongodb.adoc modules-redis.adoc modules-restassured.adoc modules-selenide.adoc modules-tm4j.adoc modules-zephyr.adoc modules.adoc FROM EXAMPLE", exampleConverter::convert);
----

[source,java]
.Converter example
----
private T convert(ResultSet rs) throws BaseException {
    try {
        T t = new T();
        t.setId(rs.getString("X__ID"));
        t.setName(rs.getString("NAME"));
        return t;
    } catch (SQLException e) {
        throw new TechnicalException(e.getLocalizedMessage());
    }
}
----

=== Methods to manage a connection

* getJdbcConnection()
* setJdbcConnection(JDBCConnection)
* close